export const roles = {

villager:{
team:"village",
nightAction:null,
receivesNightResult:false,
noResultTexts:[
"All your friends tell you that you smell, that can't be right... can it?",
"The thought of living has became rather sad.",
"You're so happy to have a wonderful day tomorrow!",
"Being called a genius isn't something very common, especially not for you.",
"Why is this matress so hard!?",
"You're scared there might be bed bugs in your bed.",
"You dreamed about cake, maybe life IS worth living...",
"You dream about a big carrot.",
"'Maybe the mafia isn't so bad?' you think to yourself...",
"Seeing a person die isn't something you really want.",
"This is the best sleep you've ever had.",
"Being in this village, you learned: 'Life isn't fair.'.",
"The night is suspiciously quiet...",
"You had a dream about a giat loaf of bread.",
"You woke up and noticed you drooled.",
"You wonder why everyone keeps calling you dumb :(",
"There's only so many people the mafia can kill, you're safe right?",
"Being a villager isn't easy, but atleast... nevermind, it's the worst.",
"Good thing you are such a deep sleeper, you didn't hear any of the screams.",
"You had a dream about the juciest apple ever.",
"Dreaming is for losers, you just see darkness."],
description:"You have no special ability. Find the mafia."
},

doctor:{
team:"village",
nightAction:"save",
receivesNightResult:false,
noResultTexts:[
"You know, being a doctor is pretty boring when nothing happens.",
"You put a needle in your patient and they aren't waking up... oh-oh.",
"The feeling of saving someones life is amazing... but how would you know?",
"You just gave your patient some pills and left. #boringdayatwork",
"Phew, having to prevent a murder would've been rough.",
"Something looks off about your patients glass of water... oh well.",
"Besides the fact your patient keeps repeating some weird phrases, all is well.",
"You fell asleep at your patients house, the wake up was kinda awkward.",
"Your patient didn't need any help tonight.",
"Nothing major with the patient tonight.",
"All seems in order with your patient.",
"Other than the weird rash, your patient seems fine.",
"Your patient seems to have an allergy to peanuts, other than that they're fine.",
"You failed to protect the right person, guilt consumes you.",
"While catering to your patient you hear a scream somewhere else..."],
description:"Choose one player each night to protect from being killed."
},

mafia:{
team:"mafia",
nightAction:"kill",
receivesNightResult:false,
noResultTexts:[
"Kill successful...",
"Your target has been killed.",
"Blood drips from the end of your knife.",
"You're not sure if the murder was successful, but judging from the screams, you're fairly sure.",
"Joining the mafia was the best decision ever!",
"Even murder is starting to get boring...",
"It's just buisiness.",
"This will be easy.",
"Why don't they ever fight back?",
"This feels almost *too* easy...",
"You're quite anxious about this kill... what if someone saw you!?",
"There's still blood on your clothes.",
"You've successfully killed them.",
"Murder, sleep, eat, repeat.",
"The mafia will be proud of you."],
teammateKillTexts:[
"They better do this right.",
"I mean... how hard can it be?",
"You are kind of annoyed you didn't get to kill instead.",
"It feels almost silly having someone else do the killing.",
"There are so many ways they could've killed, surely they didn't mess up.",
"'My gang is the best' you think to yourself as you fall asleep.",
"'Maybe the town isn't so bad?' you think to yourself...",
"You wish all nights at the job could be this peaceful.",
"Last time your partner had this job they messed up... BAD.",
"You had a dream about a big knife and an easy prey.",
"Being evil rules.",
"#thuglife",
"It feels nice not having to kill sometimes.",
"Hopefully they didn't screw up."],
description:"Work with the mafia to eliminate villagers each night."
},

sheriff:{
team:"village",
nightAction:"investigate",
receivesNightResult:true,
description:"Investigate a player each night to learn if they are suspicious."
},

mayor:{
team:"village",
nightAction:null,
receivesNightResult:false,
noResultTexts:[
"You proudly sleep as your town falls apart!",
"Money.. zzz.. money.. zzz..",
"Being this powerful isn't as easy as it looks!",
"'I am more valuable than anyone else!' you repeat in your dreams...",
"Although you're rich, you wish you could have just a LITTLE more.",
"Being a mayor can get boring at times.",
"'Doctors? Pffft- who needs -em?' you think to yourself.",
"You'll be SO angry if you die with all this money!",
"Your snoring echos through the town.",
"You sleep comfortably in your rich bed.",
"The town depends on you, remember that!",
"You dream about how rich you are.",
"It's hard sleeping with so many coins in your pockets.",
"You dream about being even more powerful.",
"'I am the best!' you think to yourself."],
description:"You have no night action, but your vote counts as 2."
},

jester:{
team:"neutral",
nightAction:null,
receivesNightResult:false,
noResultTexts:[
"This whole town is a tough crowd.",
"You're still laughing at your joke from yesterday.",
"The rest of the town must think you're crazy huh?",
"Sleeping is soooooo boring!",
"Why is there even a jester in this town if there's no king?",
"Being funny comes with it's disadvantages too, you know?",
"Would just acting like a villager get you voted out? I feel like they're dumb enough.",
"Sometimes jokes aren't funny, not in your case though.",
"You're thinking of a way to trick the town.",
"You try to sleep, but you're too excited!",
"You can't stop giggling to yourself.",
"The jingles from your suit are keeping you up.",
"Everyone seems to think you're crazy... prove them right.",
"No one understands the struggle of being insane.",
"You've been laughing at your joke for the last 5 hours."],
description:"You win if the town votes you out."
},

executioner:{
team:"neutral",
nightAction:null,
receivesNightResult:false,
noResultTexts:[
"Why does this town even need an executioner?",
"You are genuinely going to throw up if you see them again.",
"Being an executioner gets people staring, a LOT.",
"What's the point of being an executioner if you can't even execute anyone!?",
"Your target is the worst person ever, get them voted off!",
"Hopefully your target is a jester or something...",
"Okay, next morning you're killing them no matter what!",
"The hate towards your target grows stronger.",
"You want them out, now.",
"If it was legal you'd kill your target yourself.",
"The thought of having to spend even one more day with your target drives you mad.",
"Get. Them. Out.",
"You dream of a beautiful world where your target is dead.",
"Why does everyone like them so much!?"],
description:"You win if your assigned target is voted out by the town."
},

schrodingers_cat:{
team:"neutral",
nightAction:null,
receivesNightResult:false,
noResultTexts:[
"Do you even have a plan?",
"What even are your morals!?",
"You can win!",
"It's nice being a cat isn't it.",
"Got yourself killed yet?",
"Meow, meow.",
"Meow, meow, meow.",
"Your second cousin is Nyan Cat.",
"Garfield lookin' ahh.",
"I bet you like lasanga...",
"There's so many ways this game could go.",
"Meow.",
"You know, you're REALLY indecisive.",
"You curl your tail around yourself and nap.",
"You had a dream about a big fish, yum.",
"Good kitty."],
description:"You join the team of whoever tries to kill you! If you aren't in a team by the end of the game, you lose!"
},

spirit:{
team:"village",
nightAction:null,
receivesNightResult:true,
noResultTexts:[
"While it's nice to talk to ghosts, it can get rather nausiating.",
"Let's all just talk it out! Please?",
"There's too much war in the world for this.",
"Whoever kills you is screwed.",
"Murder this, lynch that, can we not just bake cookies?",
"You're one with the spirits! Make the most of it.",
"There's so much violence in this town.",
"You drift into the realm of dreams.",
"You enter the spirit realm.",
"It feels nice being so spiritually connected.",
"As you descend into dreams, you feel... free.",
"You just want peace.",
"You came to terms with the possibility that you'll die.",
"Why can't everyone just be friends?"],
description:"If you are killed at night and not saved, you may reveal one player's role to the town before morning."
},

framer:{
team:"mafia",
nightAction:"frame",
receivesNightResult:false,
noResultTexts:[
"The shadows hid your work well.",
"No one noticed your deception tonight.",
"You planted doubt and slipped away.",
"A false trail now lingers in the dark.",
"You twisted the truth without being seen.",
"The town will wake up one lie deeper.",
"You left suspicion where there was none.",
"Well, that was useless.",
"Maybe gaslighting IS the way to go...",
"'That'll get 'em'",
"You are one hell of a liar.",
"You know, at some point you'll have to stop lying...",
"Stop manipulating people.",
"There's only so many lies they can fall for."],
description:"Choose a player each night to make them appear not innocent to the Sheriff."
},

vigilante:{
team:"village",
nightAction:"vigilante_kill",
receivesNightResult:true,
noResultTexts:[
"You don't sleep tonight, you just watch the town silently.",
"You sleep with one hand on your sword.",
"You wonder whether the town will praise you or hate your for this.",
"Who are you to define justice?",
"You wrap your hand in bandages after accidentally cutting it.",
"Justice is a necessity, and if this town lacks it, you will enfore it.",
"Are you really any better than the mafia?",
"Being this familiar with killing isn't something you wanted.",
"You had a dream about a big fluffy bunny, weird...",
"You know, having a sword is pretty cool... until you have to sharpen it.",
"This life chose you.",
"Who else would've done it!?",
"You're considering calling yourself 'Stain'... you're not sure why.",
"You don't do this for fame, you do it for justice! Remember that."],
description:"At night, you may choose one player to shoot or skip. If your target is not Mafia or Neutral, you die with them."
},

priest:{
team:"village",
nightAction:"holy_shield",
receivesNightResult:true,
noResultTexts:[
"You feel evil presences all around you, this town is damned!",
"You drink some holy water to calm yourself... Much better!",
"Let's see how they like the good ol' G-O-D!",
"Bless these fools...",
"Maybe this town needs a holy grenade thrown at it...",
"You have power of God and anime on your side.",
"Feels almost silly having to protect these fools.",
"You dreamed about going to heaven, it was nice, but then you woke up here again.",
"This is all devils work!",
"In the name of God, the son, and the holy spirit!",
"You must let your peace reach out to them!",
"You are the symbol of peace this town needs.",
"One day you'll be up there with the big guy! Maybe even tomorrow...",
"There's something nice about being so spiritually connected with God."],
description:"During night, you may call upon the Holy Spirit to shield the town. If used, all kills fail that night."
},

}
